### ISSUE TITLE
Unexpected problem with functions getting a surface as argument per reference

### ISSUE THREAD

**Issue by psychon** [mikebmcl/N3888_RefImpl#27]
Hi,

I wrote the following code to create a subsurface of the surface that "context" is drawing to:

```
auto subsurface = drawing::surface(context.get_target(), 10.5, 11.0, 50.0, 50.0);
```

However, this does not work, because get_target() returns a surface by value and surface() expects a reference.

Search for "surface&" in drawing.h suggests that there are lots of other functions which cannot be given the result of get_target() or get_group_target(), e.g. the binding for create_similar_image, the surface_pattern constructor and set_source_surface().

I think that this is (loosely) related to issue #20, because e.g. move-only semantics would make the binding for create_similar_image require a reference argument...

Since this behavior was unexpected to me, I wanted to report this. Feel free to decide that this (IMO) weirdness is the way that it should be and just close this.

Cheers,
Uli

**Comment by mikebmcl** [comment]
Resolved many revisions ago. Apologies for the delay in issues processing.
