### ISSUE TITLE
Stateful drawing APIs considered harmful

### ISSUE THREAD

**Issue by seanmiddleditch** [mikebmcl/N3888_RefImpl#31]
This proposal is copying the stateful surface interfaces found in 2D canvas libraries of yester-year. We've (re)learned a lot of lessons since then as an industry and now consider that kind of implicit state stack to be harmful.

The largest issue is that the implicit state strongly hampers composability. Consider this fragment:

```
surface s;
s.set_color(red);

some_function(s);
// wait, did I have to save()/restore() around that ?
// does it break if I don't ? does it perform poorly if I do ?

s.fill(rect);
```

Function composition is severely harmed as users now have to do extra work to track the state that `surface` is bundled with, i.e. they are tracking the tracking of the state. The users have to manually deal with implementation concerns of functions they call. If the user just plays it safe and calls `save`/`restore` around any such function then they can end up with degraded efficiency (assuming they never make a mistake and forget, which real users certainly will sometimes!).

Modern graphics APIs have all moved strongly away from implicit state. In the 3D space we've seen misguided OpenGL model superceded by stateless Vulkan, and before that saw its lunch eaten by DirectX's stateless model. On 2D, the under-performing Cairo library that this paper draw inspiration from has been superceded by [Skia](https://skia.org/user/api/) or by [Azure/Moz2D](https://wiki.mozilla.org/Platform/GFX/Moz2D#Stateful_vs_stateless).

Note both of the linked APIs encode state as a separate object passed to the paint operations directly. There is no implicit state tracking in the API. A user function can only alter state if its interface explicitly takes the state as a non-const reference type, exactly as we would expect of a thoughtfully designed and mature API.

I very highly recommend reading through the design rationale of Skia or Moz2D. Cairo and Direct2D are the wrong models to base a new drawing library upon, especially one that we might want forever embedded into the C++ standard library. Stateful interfaces are bad for code composability, bad for performance, and bad for modern low-level hardware APIs.

**Comment by tyoma** [comment]
If you're interested in 2D - take a look into https://github.com/tyoma/agge. Stateless, readable, tested and 6 times faster than this io2d implementation.

**Comment by mikebmcl** [comment]
See the answer here: https://github.com/mikebmcl/N3888_RefImpl/issues/35#issuecomment-284908136 .

**Comment by mikebmcl** [comment]
Reopened for the reasons described here: https://github.com/mikebmcl/N3888_RefImpl/issues/35#issuecomment-285506484 .

Thanks for the feedback Sean and my apologies for not properly considering it until now.
