### ISSUE TITLE
Project is not compiling with the defaults settings on linux

### ISSUE THREAD

**Issue by leonid-rousniak** [mikebmcl/N3888_RefImpl#32]
The default configuration uses c++11 with gcc (but c++14 with clang), making std::make_unique impossible to compile. Running `grep -rl 'c++11' ./ | xargs sed -i 's/c++11/c++14/g'` solves the problem.

**Comment by mikebmcl** [comment]
Good catch, thanks! I will push this change very soon!

**Comment by mikebmcl** [comment]
I just tested the fix I implemented (it was c++1y to c++14, btw) using GCC 5 on OpenSUSE and it builds and runs correctly. I'm closing the issue but please let me know if the fix doesn't work for you (and if so what distro you are using and what version of GCC and libstdc++) so I can investigate further. Thank you again!
